### ISSUE TITLE
Bug in identation?

### ISSUE THREAD

**Issue by 4gus71n** [Broham/PassGen#1]
[astinx@compu PassGen]$ python3.4 passgen.py smith
  File "passgen.py", line 67
    pwList += "".join(password) + '\n'
                                     ^
TabError: inconsistent use of tabs and spaces in indentation

**Comment by Broham** [comment]
Looks like a couple of indents used spaces and tabs which may have caused the problem.  Just updated and pushed.  Try pulling the latest and let me know if you are still having the issue.
